/* tslint:disable */
/* eslint-disable */
/**
 * Template Service
 * This is a Template YAML For Microservices
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Template } from './Template';
import {
    TemplateFromJSON,
    TemplateFromJSONTyped,
    TemplateToJSON,
} from './Template';

/**
 * This is a TemplateChild object that extends Template
 * @export
 * @interface TemplateFull
 */
export interface TemplateFull extends Template {
    /**
     * 
     * @type {number}
     * @memberof TemplateFull
     */
    id?: number;
}

/**
 * Check if a given object implements the TemplateFull interface.
 */
export function instanceOfTemplateFull(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplateFullFromJSON(json: any): TemplateFull {
    return TemplateFullFromJSONTyped(json, false);
}

export function TemplateFullFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateFull {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...TemplateFromJSONTyped(json, ignoreDiscriminator),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function TemplateFullToJSON(value?: TemplateFull | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...TemplateToJSON(value),
        'id': value.id,
    };
}

